site_name: IT50

theme:
  language: en
  name: material
  features:
    - navigaion.instant
    - navigation.tabs
    - navigation.indexes

nav:
  - About: en/
  - Book: en/data

extra:
  alternate:
    - name: English
      link: /en/
      lang: en

    - name: 中文（简体）
      link: /zh-Hans/
      lang: zh

markdown_extensions:
  - extra
  - meta
  - def_list
