site_name: IT50

theme:
  language: en
  name: material
  features:
    - navigaion.instant
    - navigation.tabs
    - navigation.indexes
  # palette:
  #   - scheme: it50
  # logo: /static/assets/icon.svg
  # favicon: /static/assets/icon.svg
  # font:
  #   text: Mukta

nav:
  - About: en/
  - Book:
    - Data:
      - Overview: en/data.md
      - Binary Data: en/binary-data.md
      - Text Encoding: en/text-encoding.md
      - File Format: en/file-format.md
      - Partitioning and Filesystem: en/partitioning-and-filesystem.md
    - Program:
      - Overview: en/program.md
    - Cryptography:
      - Overview: en/cryptography.md
      - Cryptographic Hash: en/cryptographic-hash.md
      - Symmetric Cryptogtaphy: en/symmetric-cryptography.md
      - Asymmetric Cryptography: en/asymmetric-cryptography.md
      - Public Key Infrastructure: en/public-key-infrastructure.md
    - Network:
      - Overview: none

extra:
  homepage: /en/
  alternate:
    - name: English
      link: /en/
      lang: en

    - name: 中文（简体）
      link: /zh-Hans/
      lang: zh

extra_css:
  - /static/stylesheets/features.css
  # - /static/stylesheets/dimensions.css
  # - /static/stylesheets/colors.css

markdown_extensions:
  - extra
  - meta
  - def_list
