site_name: IT50

theme:
  language: en
  name: material
  features:
    - navigaion.instant
    - navigation.tabs
    - navigation.indexes

nav:
  - About: /en/
  - Theory:
    - Data:
      - Overview: /en/theory/data.md
      - Binary Data: /en/theory/binary-data.md
      - Text Encoding: /en/theory/text-encoding.md
      - File Format: /en/theory/file-format.md
      - Partitioning and Filesystem: /en/theory/partitioning-and-filesystem.md
    - Program:
      - Overview: /en/theory/program.md
    - Cryptography:
      - Overview: /en/theory/cryptography.md
      - Cryptographic Hash: /en/theory/cryptographic-hash.md
      - Symmetric Cryptogtaphy: /en/theory/symmetric-cryptography.md
      - Asymmetric Cryptography: /en/theory/asymmetric-cryptography.md
      - Public Key Infrastructure: /en/theory/public-key-infrastructure.md
    - Network:
      - Overview: none

extra:
  homepage: /en/
  alternate:
    - name: English
      link: /en/
      lang: en

    - name: 中文（简体）
      link: /zh-Hans/
      lang: zh

markdown_extensions:
  - extra
  - meta
  - def_list
