site_name: IT50

theme:
  language: zh
  name: material
  features:
    - navigaion.instant
    - navigation.tabs
    - navigation.indexes
  # palette:
  #   - scheme: it50
  # logo: /static/assets/icon.svg
  # favicon: /static/assets/icon.svg
  # font:
  #   text: Mukta

nav:
  - 关于: zh-Hans/
  - 书:
    - 介绍: zh-Hans/introduction.md
    - 数据: zh-Hans/data.md
    - 文字编码: zh-Hans/text-encoding.md

extra:
  homepage: /zh-Hans/
  alternate:
    - name: English
      link: /en/
      lang: en

    - name: 中文（简体）
      link: /zh-Hans/
      lang: zh

extra_css:
  - /static/stylesheets/features.css
  # - /static/stylesheets/dimensions.css
  # - /static/stylesheets/colors.css

markdown_extensions:
  - extra
  - meta
  - def_list
