site_name: IT50

theme:
  language: zh
  name: material
  features:
    - navigaion.instant
    - navigation.tabs
    - navigation.indexes

nav:
  - 关于: zh-Hans/
  - 书:
    - 数据:
      - 概览: zh-Hans/data.md
      - 二进制数据: zh-Hans/binary-data.md
      - 文字编码: zh-Hans/text-encoding.md
      - 文件格式: zh-Hans/file-format.md
      - 分区和文件系统: zh-Hans/partitioning-and-filesystem.md
    - 程序:
      - 概览: zh-Hans/program.md
    - 密码学:
      - 概览: zh-Hans/cryptography.md
      - 密码学哈希: zh-Hans/cryptographic-hash.md
      - 对称密码学: zh-Hans/symmetric-cryptography.md
      - 非对称密码学: zh-Hans/asymmetric-cryptography.md
      - 公钥基础设施: zh-Hans/public-key-infrastructure.md
    - 网络:
      - 概览: none

extra:
  homepage: /zh-Hans/
  alternate:
    - name: English
      link: /en/
      lang: en

    - name: 中文（简体）
      link: /zh-Hans/
      lang: zh

markdown_extensions:
  - extra
  - meta
  - def_list
